import {useCallback,useEffect,useState} from 'react'
import {MapView} from './MapView'
import {RainCanvas} from './RainCanvas'
import {Tutorial} from './Tutorial'
import type {Comparison,Scenario} from './types'
const riskLabel={normal:'Stable',watch:'Watch',high:'High',critical:'Critical'}
type Segment={minute:number;rainfall_mmh:number}

export function App(){
 const[rain,setRain]=useState(38),[data,setData]=useState<Scenario|null>(null),[minute,setMinute]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1)
 const[selected,setSelected]=useState('OX-103'),[inspectionOpen,setInspectionOpen]=useState(true),[comparison,setComparison]=useState<Comparison|null>(null),[loading,setLoading]=useState(true),[tutorial,setTutorial]=useState(true)
 const requestScenario=useCallback(async(body:Record<string,unknown>)=>{const r=await fetch('/api/scenarios/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return await r.json() as Scenario},[])
 useEffect(()=>{requestScenario({rainfall_mmh:38,duration_minutes:90,rainfall_schedule:[{minute:0,rainfall_mmh:38}]}).then(setData).finally(()=>setLoading(false))},[requestScenario])
 useEffect(()=>{if(!playing||!data)return;const t=setInterval(()=>setMinute(m=>m+1),1000/speed);return()=>clearInterval(t)},[playing,data,speed])
 useEffect(()=>{if(!data||loading||minute<data.scenario.duration_minutes-15)return;setLoading(true);requestScenario({rainfall_mmh:data.scenario.rainfall_mmh,duration_minutes:data.scenario.duration_minutes+90,rainfall_schedule:data.scenario.rainfall_schedule,interventions:data.scenario.interventions}).then(setData).finally(()=>setLoading(false))},[minute,data,loading,requestScenario])
 async function applyRain(){if(!data)return;setLoading(true);const effectiveMinute=minute+1;const schedule:Segment[]=[...data.scenario.rainfall_schedule.filter(s=>s.minute!==effectiveMinute),{minute:effectiveMinute,rainfall_mmh:rain}].sort((a,b)=>a.minute-b.minute);const next=await requestScenario({rainfall_mmh:schedule[0].rainfall_mmh,duration_minutes:Math.max(data.scenario.duration_minutes,effectiveMinute+90),rainfall_schedule:schedule,interventions:data.scenario.interventions});setData(next);setComparison(null);setLoading(false)}
 async function dispatch(){if(!data)return;setLoading(true);try{const r=await fetch('/api/scenarios/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rainfall_mmh:data.scenario.rainfall_mmh,rainfall_schedule:data.scenario.rainfall_schedule,interventions:data.scenario.interventions,duration_minutes:data.scenario.duration_minutes,drain_id:selected,cleaning_minute:minute})});if(!r.ok)throw new Error(await r.text());const c=await r.json() as Comparison;setComparison(c);setData(c.intervention);setPlaying(true)}catch(error){console.error('Could not dispatch crew',error)}finally{setLoading(false)}}
 if(!data)return <div className="loading">Calibrating Oxford scenario…</div>
 const frame=data.timeline[Math.min(minute,data.timeline.length-1)],state=frame.drains.find(x=>x.id===selected),drain=data.network.drains.find(x=>x.id===selected),asset=data.network.assets.find(x=>x.id===drain?.asset)
 const critical=frame.drains.filter(x=>x.risk==='critical'||x.risk==='high').length,currentRain=frame.rainfall_mmh??rain
 const failureLog=data.timeline.slice(0,minute+1).flatMap(eventFrame=>eventFrame.drains.filter(x=>x.overflow_at_minute===eventFrame.minute))
 const liveRecommendation=frame.recommendation
 const sensorReadings=data.timeline.slice(Math.max(0,minute-17),minute+1).map((f,i)=>({x:i*6,y:32-(f.drains.find(x=>x.id===selected)?.water_level_cm??0)*.48}))
 const sensorHistory=sensorReadings.map(p=>`${p.x},${p.y}`).join(' '),sensorLast=sensorReadings[sensorReadings.length-1]
 const statusPrimary=state?.overflow_m3?'Overflow':state?.risk==='critical'||state?.risk==='high'?'Almost full':state?.risk==='watch'?'Watch':'Stable'
 return <main><header><div className="scene-title"><b>Rain &amp; drains</b></div><div className="speed-controls" aria-label="Simulation speed">{[.5,1,2].map(value=><button key={value} className={speed===value?'active':''} onClick={()=>setSpeed(value)}>×{value}</button>)}</div><div className="clock"><i className="clock-face"/><b>{minute} min</b><button className="tour-help" onClick={()=>setTutorial(true)} aria-label="Open tutorial">?</button></div></header>
 <section className={`workspace ${inspectionOpen?'':'inspection-closed'}`}><div className="map-wrap"><MapView drains={data.network.drains} assets={data.network.assets} states={frame.drains} selected={selected} priorityId={liveRecommendation.requires_action?liveRecommendation.drain_id:null} onSelect={id=>{setSelected(id);setInspectionOpen(true)}}/><RainCanvas intensity={rain} running={playing} water={frame.drains.reduce((s,d)=>s+d.overflow_m3,0)}/><div className="map-caption"><b>West Oxford</b></div><div className="legend"><span><i className="normal"/>clear</span><span><i className="watch"/>watch</span><span><i className="high"/>almost full</span><span><i className="critical"/>overflow</span></div></div>
 {inspectionOpen&&<aside><div className="aside-head"><button onClick={()=>setInspectionOpen(false)}>×</button></div><div className="asset-title"><small>{selected}</small><h1>{drain?.name}</h1><div className="sensor-stack"><div className="telemetry"><div><i/><code>{state?.sensor_id} · RX #{state?.sensor_packet}</code><b>{state?.water_level_cm} cm</b></div><svg viewBox="0 0 102 36" preserveAspectRatio="none"><path className="sensor-grid" d="M0 8H102M0 20H102M0 32H102"/><polyline points={sensorHistory}/>{sensorLast&&<circle cx={sensorLast.x} cy={sensorLast.y} r="2"/>}</svg></div><div className={`vision-feed ${state?.camera_status}`}><div><i/><code>{state?.camera_id}</code><b>{state?.camera_status==='restoring_connection'?'Restoring connection':'Recording'}</b></div><small>recognition confidence <strong>{state?.camera_status==='restoring_connection'?'—':`${state?.vision_confidence_pct}%`}</strong></small></div></div></div>
 <div className="instrument"><div><label><b>{state?.fill_pct}%</b> water held</label><meter min="0" max="100" value={state?.fill_pct}/></div><div><label><b>{state?.blockage_pct}%</b> inlet covered</label><meter min="0" max="100" value={state?.blockage_pct}/></div></div><div className={`risk-line ${state?.risk}`}><span>status:</span><strong>{statusPrimary}</strong></div>
 <div className="recommendation">{liveRecommendation.drain_id===selected?<button onClick={dispatch} disabled={loading}>{!loading&&<svg className="crew-icon" viewBox="0 0 32 18" aria-hidden="true"><path d="M2 4h17v10H2zM19 7h6l5 5v2H19z"/><circle cx="8" cy="15" r="2.5"/><circle cx="24" cy="15" r="2.5"/></svg>}<span>{loading?'…':`Send crew to ${selected}`}</span><b>→</b></button>:<p>{liveRecommendation.drain_id} comes first.</p>}</div>{comparison&&<div className="impact"><b>−{comparison.impact.prevented_overflow_m3} m³</b><p>kept off the street</p></div>}</aside>}</section>
 <footer><div className="weather"><label>Rain <b>{rain} mm/h</b></label><input type="range" min="0" max="70" value={rain} onChange={e=>setRain(+e.target.value)} onPointerUp={applyRain}/></div><button className="play" onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ':'▶'}</button><div className="failure-log"><label>Overflow notes</label>{failureLog.length?failureLog.map(x=><div key={x.id}><b>{x.id}</b><span>{Math.floor(x.overflow_at_minute!/60).toString().padStart(2,'0')}:{String(x.overflow_at_minute!%60).padStart(2,'0')}</span></div>):<p>No overflows yet.</p>}</div></footer>{tutorial&&<Tutorial onClose={()=>setTutorial(false)}/>}</main>
}
